<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = array(
            array('productName' => 'iPhone', 'business_id' => '1', 'unit_id' => '7', 'brand_id' => '19', 'category_id' => '15', 'productCode' => '0001777', 'productPicture' => 'uploads/25/08/1754893914-832.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '20', 'profit_percent' => '0', 'vat_amount' => '0.00', 'vat_type' => 'inclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:44:38', 'updated_at' => '2025-08-11 18:31:54', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
            array('productName' => 'Laptop', 'business_id' => '1', 'unit_id' => '7', 'brand_id' => '19', 'category_id' => '15', 'productCode' => '0002', 'productPicture' => 'uploads/25/08/1754894080-870.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '5', 'profit_percent' => '0', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:46:05', 'updated_at' => '2025-08-11 18:34:40', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
            array('productName' => 'Shoe', 'business_id' => '1', 'unit_id' => '2', 'brand_id' => '21', 'category_id' => '19', 'productCode' => '0003', 'productPicture' => 'uploads/25/08/1754893657-989.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '20', 'profit_percent' => '0', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:47:25', 'updated_at' => '2025-08-11 18:27:37', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
            array('productName' => 'Banana', 'business_id' => '1', 'unit_id' => '2', 'brand_id' => '22', 'category_id' => '17', 'productCode' => '0004', 'productPicture' => 'uploads/25/08/1754891335-373.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '5', 'profit_percent' => '0', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:48:55', 'updated_at' => '2025-08-11 17:48:55', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
            array('productName' => 'Ladies  Bag', 'business_id' => '1', 'unit_id' => '2', 'brand_id' => '19', 'category_id' => '19', 'productCode' => '0005', 'productPicture' => 'uploads/25/08/1754891421-621.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '2', 'profit_percent' => '0', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:50:21', 'updated_at' => '2025-08-11 17:50:21', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
            array('productName' => 'Watch', 'business_id' => '1', 'unit_id' => '2', 'brand_id' => '20', 'category_id' => '19', 'productCode' => '0006', 'productPicture' => 'uploads/25/08/1754891510-120.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '6', 'profit_percent' => '0', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:51:50', 'updated_at' => '2025-08-11 17:51:50', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
            array('productName' => 'T-shirt', 'business_id' => '1', 'unit_id' => '2', 'brand_id' => '19', 'category_id' => '19', 'productCode' => '0007', 'productPicture' => 'uploads/25/08/1754894062-591.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '5', 'profit_percent' => '0', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:55:42', 'updated_at' => '2025-08-11 18:34:22', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
            array('productName' => 'Nike Structure 25', 'business_id' => '1', 'unit_id' => '7', 'brand_id' => '18', 'category_id' => '19', 'productCode' => '0008', 'productPicture' => 'uploads/25/08/1754891870-554.png', 'product_type' => 'single', 'productDealerPrice' => '0.00', 'productPurchasePrice' => '0.00', 'productSalePrice' => '0.00', 'productWholeSalePrice' => '0.00', 'productStock' => '0.00', 'expire_date' => NULL, 'alert_qty' => '20', 'profit_percent' => '0', 'vat_amount' => '0.39', 'vat_type' => 'inclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => NULL, 'meta' => NULL, 'created_at' => '2025-08-11 17:57:50', 'updated_at' => '2025-08-11 18:12:53', 'vat_id' => NULL, 'model_id' => NULL, 'warehouse_id' => NULL),
        );

        Product::insert($products);
    }
}
